#============================================
#         Configs for localhost:
#============================================

#Datasourse props
spring:
  datasource:
    url: jdbc:mysql://10.10.0.4:3306/bike_championship?useUnicode=true&characterEncoding=utf8&useSSL=false&verifyServerCertificate=false
    username: bike_championship
    password: bike_championship
  jpa:
    hibernate:
      ddl-auto: create-drop

#Jwt properties
jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000

#Cors constants
cors:
  origin: "*"
