#============================================
#         Configs for localhost:
#============================================

#Datasourse props
spring:
  datasource:
    url: jdbc:mysql://db:3306/bikechampionship?useUnicode=true&characterEncoding=utf8&useSSL=false&verifyServerCertificate=false
    username: bikechampionship
    password: bikechampionship
  jpa:
    hibernate:
      ddl-auto: create-drop

#Jwt properties
jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000

#Cors constants
cors:
  origin: "*"
